## Intro to the Xarray Module - Fetch Panel Dataset from Google - Dimensions
This panel object has been deprecated. Recommended to use Xarray instead.

A Panel object is a three-dimensional datastructure. We now need 3 points of reference in order to locate any specific value inside a panel object. It's a box of DFs. Need what the DF is, the row and column intersection in order to extract a single value.

### Dimensions refresher
Vending machine. One column of choices (5 sodas). If a person wants a soda, they just need to provide one point of reference, e.g., "I want the soda that's in row position 2." -- This is like a SERIES - just need to row label or the row number.

DATAFRAMES vending machine is the clear kind where you see all the drinks lined up in rows and columns. I want the soda in row 2 is NOT ENOUGH. We could have 10 different choices in that row (or column). Therefore, they must provide TWO points of reference that we know exactly what they want. This is a two-dimensional object. Need to give Row AND Column.

PANEL is one step up. It is a three-dimensional object so we need to provide three points of reference.



In [26]:
import pandas as pd
import pandas_datareader.data as web
import xarray as xr

In [29]:
companies = ["TCEHY", "BABA", "GOOG", "AAPL", "AMZN"]

p = web.DataReader(name = companies, data_source = "morningstar",
               start = "2010-01-01", end = "2016-12-31")

p.head()  # Returns standard DF

Close   High    Low   Open  Volume
Symbol Date                                          
TCEHY  2010-01-01  4.344  4.366  4.320  4.320       0
       2010-01-04  4.416  4.416  4.366  4.366   61480
       2010-01-05  4.452  4.480  4.410  4.474   75690
       2010-01-06  4.482  4.482  4.470  4.480   56010
       2010-01-07  4.300  4.300  4.254  4.298   49355

In [11]:
type(p)

pandas.core.frame.DataFrame

In [39]:
# Need to run p = p.to_xarray() to convert DF to XR
# We basically have 5 DFs or Datasets (XR term). 
# HOw to find out values? 
p

<xarray.Dataset>
Dimensions:  (Date: 1826, Symbol: 5)
Coordinates:
  * Symbol   (Symbol) object 'AAPL' 'AMZN' 'BABA' 'GOOG' 'TCEHY'
  * Date     (Date) datetime64[ns] 2010-01-01 2010-01-04 2010-01-05 ...
Data variables:
    Close    (Symbol, Date) float64 30.1 30.57 30.63 30.14 30.08 30.28 30.02 ...
    High     (Symbol, Date) float64 30.48 30.64 30.8 30.75 30.29 30.29 30.43 ...
    Low      (Symbol, Date) float64 30.08 30.34 30.46 30.11 29.86 29.87 ...
    Open     (Symbol, Date) float64 30.44 30.5 30.68 30.63 30.24 30.06 30.42 ...
    Volume   (Symbol, Date) float64 0.0 1.234e+08 1.505e+08 1.38e+08 ...

In [46]:
p.items  # The Data variables (items axis) are 5 DFs/Datasets in the Xarray

<bound method Mapping.items of <xarray.Dataset>
Dimensions:  (Date: 1826, Symbol: 5)
Coordinates:
  * Symbol   (Symbol) object 'AAPL' 'AMZN' 'BABA' 'GOOG' 'TCEHY'
  * Date     (Date) datetime64[ns] 2010-01-01 2010-01-04 2010-01-05 ...
Data variables:
    Close    (Symbol, Date) float64 30.1 30.57 30.63 30.14 30.08 30.28 30.02 ...
    High     (Symbol, Date) float64 30.48 30.64 30.8 30.75 30.29 30.29 30.43 ...
    Low      (Symbol, Date) float64 30.08 30.34 30.46 30.11 29.86 29.87 ...
    Open     (Symbol, Date) float64 30.44 30.5 30.68 30.63 30.24 30.06 30.42 ...
    Volume   (Symbol, Date) float64 0.0 1.234e+08 1.505e+08 1.38e+08 ...>

In [45]:
# Want to pull out the list of all the dates
p.Date  # Returns the rows for the Date DF/Dataset

<xarray.DataArray 'Date' (Date: 1826)>
array(['2010-01-01T00:00:00.000000000', '2010-01-04T00:00:00.000000000',
       '2010-01-05T00:00:00.000000000', ..., '2016-12-28T00:00:00.000000000',
       '2016-12-29T00:00:00.000000000', '2016-12-30T00:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * Date     (Date) datetime64[ns] 2010-01-01 2010-01-04 2010-01-05 ...

In [43]:
p.Symbol # These 5 companies are the columns

<xarray.DataArray 'Symbol' (Symbol: 5)>
array(['AAPL', 'AMZN', 'BABA', 'GOOG', 'TCEHY'], dtype=object)
Coordinates:
  * Symbol   (Symbol) object 'AAPL' 'AMZN' 'BABA' 'GOOG' 'TCEHY'

In [47]:
p.Close  # I think the .Close (part of Data variables) is the same as minor_axis

<xarray.DataArray 'Close' (Symbol: 5, Date: 1826)>
array([[ 30.1046,  30.5729,  30.6257, ..., 116.76  , 116.73  , 115.82  ],
       [134.52  , 133.9   , 134.69  , ..., 772.13  , 765.15  , 749.87  ],
       [     nan,      nan,      nan, ...,  87.37  ,  87.33  ,  87.81  ],
       [     nan,      nan,      nan, ..., 785.05  , 782.79  , 771.82  ],
       [  4.344 ,   4.416 ,   4.452 , ...,  23.544 ,  24.36  ,  24.22  ]])
Coordinates:
  * Symbol   (Symbol) object 'AAPL' 'AMZN' 'BABA' 'GOOG' 'TCEHY'
  * Date     (Date) datetime64[ns] 2010-01-01 2010-01-04 2010-01-05 ...

In [50]:
# Need 3 points of reference in order to pull a value Symbol, Date, Data (volume, open, etc.)
p.all

<bound method ImplementsDatasetReduce._reduce_method.<locals>.wrapped_func of <xarray.Dataset>
Dimensions:  (Date: 1826, Symbol: 5)
Coordinates:
  * Symbol   (Symbol) object 'AAPL' 'AMZN' 'BABA' 'GOOG' 'TCEHY'
  * Date     (Date) datetime64[ns] 2010-01-01 2010-01-04 2010-01-05 ...
Data variables:
    Close    (Symbol, Date) float64 30.1 30.57 30.63 30.14 30.08 30.28 30.02 ...
    High     (Symbol, Date) float64 30.48 30.64 30.8 30.75 30.29 30.29 30.43 ...
    Low      (Symbol, Date) float64 30.08 30.34 30.46 30.11 29.86 29.87 ...
    Open     (Symbol, Date) float64 30.44 30.5 30.68 30.63 30.24 30.06 30.42 ...
    Volume   (Symbol, Date) float64 0.0 1.234e+08 1.505e+08 1.38e+08 ...>

## Xarray Attributes
p.indexes returns all of the axes/indices of the XR object with dates returned as a DateTimeIndex. Also have p.all, p.items, etc.

.coords = Coordinates (Symbol & Date)
.data_vars = Data variables (Close, High, Low, Open, Volume)

What's the Xarray equivalent to p.axes? or ndim? Check out http://xarray.pydata.org/en/stable/api.html for details/attributes.

Panels require 3 points of data: 1. Item - a DF, 2. A row label, 3. A column label. Have to test out xarray



In [51]:
companies = ["TCEHY", "BABA", "GOOG", "AAPL", "AMZN"]

p = web.DataReader(name = companies, data_source = "morningstar",
               start = "2010-01-01", end = "2016-12-31")

p.head()  # Returns standard DF
p = p.to_xarray()

In [55]:
p.indexes

Symbol: Index(['AAPL', 'AMZN', 'BABA', 'GOOG', 'TCEHY'], dtype='object', name='Symbol')
Date: DatetimeIndex(['2010-01-01', '2010-01-04', '2010-01-05', '2010-01-06',
                     '2010-01-07', '2010-01-08', '2010-01-11', '2010-01-12',
                     '2010-01-13', '2010-01-14',
                     ...
                     '2016-12-19', '2016-12-20', '2016-12-21', '2016-12-22',
                     '2016-12-23', '2016-12-26', '2016-12-27', '2016-12-28',
                     '2016-12-29', '2016-12-30'],
                    dtype='datetime64[ns]', name='Date', length=1826, freq=None)

In [56]:
p.all

<bound method ImplementsDatasetReduce._reduce_method.<locals>.wrapped_func of <xarray.Dataset>
Dimensions:  (Date: 1826, Symbol: 5)
Coordinates:
  * Symbol   (Symbol) object 'AAPL' 'AMZN' 'BABA' 'GOOG' 'TCEHY'
  * Date     (Date) datetime64[ns] 2010-01-01 2010-01-04 2010-01-05 ...
Data variables:
    Close    (Symbol, Date) float64 30.1 30.57 30.63 30.14 30.08 30.28 30.02 ...
    High     (Symbol, Date) float64 30.48 30.64 30.8 30.75 30.29 30.29 30.43 ...
    Low      (Symbol, Date) float64 30.08 30.34 30.46 30.11 29.86 29.87 ...
    Open     (Symbol, Date) float64 30.44 30.5 30.68 30.63 30.24 30.06 30.42 ...
    Volume   (Symbol, Date) float64 0.0 1.234e+08 1.505e+08 1.38e+08 ...>

In [58]:
p.data_vars

Data variables:
    Close    (Symbol, Date) float64 30.1 30.57 30.63 30.14 30.08 30.28 30.02 ...
    High     (Symbol, Date) float64 30.48 30.64 30.8 30.75 30.29 30.29 30.43 ...
    Low      (Symbol, Date) float64 30.08 30.34 30.46 30.11 29.86 29.87 ...
    Open     (Symbol, Date) float64 30.44 30.5 30.68 30.63 30.24 30.06 30.42 ...
    Volume   (Symbol, Date) float64 0.0 1.234e+08 1.505e+08 1.38e+08 ...

In [59]:
p.coords 

Coordinates:
  * Symbol   (Symbol) object 'AAPL' 'AMZN' 'BABA' 'GOOG' 'TCEHY'
  * Date     (Date) datetime64[ns] 2010-01-01 2010-01-04 2010-01-05 ...

In [63]:
# .ndim -- number of dimensions in the panel
# XR equiv? not sure
p.dims  # SortedKeysDict??

Frozen(SortedKeysDict({'Symbol': 5, 'Date': 1826}))

In [65]:
p.keys

<bound method Mapping.keys of <xarray.Dataset>
Dimensions:  (Date: 1826, Symbol: 5)
Coordinates:
  * Symbol   (Symbol) object 'AAPL' 'AMZN' 'BABA' 'GOOG' 'TCEHY'
  * Date     (Date) datetime64[ns] 2010-01-01 2010-01-04 2010-01-05 ...
Data variables:
    Close    (Symbol, Date) float64 30.1 30.57 30.63 30.14 30.08 30.28 30.02 ...
    High     (Symbol, Date) float64 30.48 30.64 30.8 30.75 30.29 30.29 30.43 ...
    Low      (Symbol, Date) float64 30.08 30.34 30.46 30.11 29.86 29.87 ...
    Open     (Symbol, Date) float64 30.44 30.5 30.68 30.63 30.24 30.06 30.42 ...
    Volume   (Symbol, Date) float64 0.0 1.234e+08 1.505e+08 1.38e+08 ...>

In [68]:
p.values

<bound method Mapping.values of <xarray.Dataset>
Dimensions:  (Date: 1826, Symbol: 5)
Coordinates:
  * Symbol   (Symbol) object 'AAPL' 'AMZN' 'BABA' 'GOOG' 'TCEHY'
  * Date     (Date) datetime64[ns] 2010-01-01 2010-01-04 2010-01-05 ...
Data variables:
    Close    (Symbol, Date) float64 30.1 30.57 30.63 30.14 30.08 30.28 30.02 ...
    High     (Symbol, Date) float64 30.48 30.64 30.8 30.75 30.29 30.29 30.43 ...
    Low      (Symbol, Date) float64 30.08 30.34 30.46 30.11 29.86 29.87 ...
    Open     (Symbol, Date) float64 30.44 30.5 30.68 30.63 30.24 30.06 30.42 ...
    Volume   (Symbol, Date) float64 0.0 1.234e+08 1.505e+08 1.38e+08 ...>

In [69]:
p.High

<xarray.DataArray 'High' (Symbol: 5, Date: 1826)>
array([[ 30.4786,  30.6429,  30.7986, ..., 118.0166, 117.1095, 117.2   ],
       [137.28  , 136.61  , 135.479 , ..., 780.    , 773.4   , 767.3999],
       [     nan,      nan,      nan, ...,  88.75  ,  88.2   ,  88.1   ],
       [     nan,      nan,      nan, ..., 794.23  , 785.93  , 782.78  ],
       [  4.366 ,   4.416 ,   4.48  , ...,  23.78  ,  24.43  ,  24.5   ]])
Coordinates:
  * Symbol   (Symbol) object 'AAPL' 'AMZN' 'BABA' 'GOOG' 'TCEHY'
  * Date     (Date) datetime64[ns] 2010-01-01 2010-01-04 2010-01-05 ...

In [70]:
p.dims

Frozen(SortedKeysDict({'Symbol': 5, 'Date': 1826}))

In [71]:
p.attrs

OrderedDict()

In [72]:
p.High.values

array([[ 30.4786,  30.6429,  30.7986, ..., 118.0166, 117.1095, 117.2   ],
       [137.28  , 136.61  , 135.479 , ..., 780.    , 773.4   , 767.3999],
       [     nan,      nan,      nan, ...,  88.75  ,  88.2   ,  88.1   ],
       [     nan,      nan,      nan, ..., 794.23  , 785.93  , 782.78  ],
       [  4.366 ,   4.416 ,   4.48  , ...,  23.78  ,  24.43  ,  24.5   ]])

In [73]:
type(p.High.values)

numpy.ndarray

In [74]:
p.High.dims

('Symbol', 'Date')

In [75]:
p.Volume.attrs

OrderedDict()

In [78]:
p.Close.attrs

OrderedDict()

In [79]:
p.dims

Frozen(SortedKeysDict({'Symbol': 5, 'Date': 1826}))

In [82]:
p.indexes

Symbol: Index(['AAPL', 'AMZN', 'BABA', 'GOOG', 'TCEHY'], dtype='object', name='Symbol')
Date: DatetimeIndex(['2010-01-01', '2010-01-04', '2010-01-05', '2010-01-06',
                     '2010-01-07', '2010-01-08', '2010-01-11', '2010-01-12',
                     '2010-01-13', '2010-01-14',
                     ...
                     '2016-12-19', '2016-12-20', '2016-12-21', '2016-12-22',
                     '2016-12-23', '2016-12-26', '2016-12-27', '2016-12-28',
                     '2016-12-29', '2016-12-30'],
                    dtype='datetime64[ns]', name='Date', length=1826, freq=None)

In [83]:
p.values

<bound method Mapping.values of <xarray.Dataset>
Dimensions:  (Date: 1826, Symbol: 5)
Coordinates:
  * Symbol   (Symbol) object 'AAPL' 'AMZN' 'BABA' 'GOOG' 'TCEHY'
  * Date     (Date) datetime64[ns] 2010-01-01 2010-01-04 2010-01-05 ...
Data variables:
    Close    (Symbol, Date) float64 30.1 30.57 30.63 30.14 30.08 30.28 30.02 ...
    High     (Symbol, Date) float64 30.48 30.64 30.8 30.75 30.29 30.29 30.43 ...
    Low      (Symbol, Date) float64 30.08 30.34 30.46 30.11 29.86 29.87 ...
    Open     (Symbol, Date) float64 30.44 30.5 30.68 30.63 30.24 30.06 30.42 ...
    Volume   (Symbol, Date) float64 0.0 1.234e+08 1.505e+08 1.38e+08 ...>

## Use bracket notation to extract a DataFrame (for Subsetting)
**Important** Used to extract the next smallest object. In a series, we extract a value. In a DF, you use bracket notation to extract a column, which is a series/1D object.

Same for panel/xarray - used to extract a DF/Dataset.

In [86]:
p.items
p.data_vars

Data variables:
    Close    (Symbol, Date) float64 30.1 30.57 30.63 30.14 30.08 30.28 30.02 ...
    High     (Symbol, Date) float64 30.48 30.64 30.8 30.75 30.29 30.29 30.43 ...
    Low      (Symbol, Date) float64 30.08 30.34 30.46 30.11 29.86 29.87 ...
    Open     (Symbol, Date) float64 30.44 30.5 30.68 30.63 30.24 30.06 30.42 ...
    Volume   (Symbol, Date) float64 0.0 1.234e+08 1.505e+08 1.38e+08 ...

In [88]:
p['Open']

<xarray.DataArray 'Open' (Symbol: 5, Date: 1826)>
array([[ 30.4443,  30.5   ,  30.6843, ..., 117.52  , 116.45  , 116.65  ],
       [137.08  , 136.28  , 133.25  , ..., 776.25  , 772.4   , 766.47  ],
       [     nan,      nan,      nan, ...,  88.3   ,  87.82  ,  87.57  ],
       [     nan,      nan,      nan, ..., 793.7   , 783.33  , 782.75  ],
       [  4.32  ,   4.366 ,   4.474 , ...,  23.65  ,  24.155 ,  24.5   ]])
Coordinates:
  * Symbol   (Symbol) object 'AAPL' 'AMZN' 'BABA' 'GOOG' 'TCEHY'
  * Date     (Date) datetime64[ns] 2010-01-01 2010-01-04 2010-01-05 ...

In [90]:
p.data_vars["Open"]

<xarray.DataArray 'Open' (Symbol: 5, Date: 1826)>
array([[ 30.4443,  30.5   ,  30.6843, ..., 117.52  , 116.45  , 116.65  ],
       [137.08  , 136.28  , 133.25  , ..., 776.25  , 772.4   , 766.47  ],
       [     nan,      nan,      nan, ...,  88.3   ,  87.82  ,  87.57  ],
       [     nan,      nan,      nan, ..., 793.7   , 783.33  , 782.75  ],
       [  4.32  ,   4.366 ,   4.474 , ...,  23.65  ,  24.155 ,  24.5   ]])
Coordinates:
  * Symbol   (Symbol) object 'AAPL' 'AMZN' 'BABA' 'GOOG' 'TCEHY'
  * Date     (Date) datetime64[ns] 2010-01-01 2010-01-04 2010-01-05 ...

In [91]:
p

<xarray.Dataset>
Dimensions:  (Date: 1826, Symbol: 5)
Coordinates:
  * Symbol   (Symbol) object 'AAPL' 'AMZN' 'BABA' 'GOOG' 'TCEHY'
  * Date     (Date) datetime64[ns] 2010-01-01 2010-01-04 2010-01-05 ...
Data variables:
    Close    (Symbol, Date) float64 30.1 30.57 30.63 30.14 30.08 30.28 30.02 ...
    High     (Symbol, Date) float64 30.48 30.64 30.8 30.75 30.29 30.29 30.43 ...
    Low      (Symbol, Date) float64 30.08 30.34 30.46 30.11 29.86 29.87 ...
    Open     (Symbol, Date) float64 30.44 30.5 30.68 30.63 30.24 30.06 30.42 ...
    Volume   (Symbol, Date) float64 0.0 1.234e+08 1.505e+08 1.38e+08 ...

In [94]:
p.loc["AMZN", "Close", "2010-01-01"]

TypeError: can only lookup dictionaries from Dataset.loc

## Extracting with the .loc[], .iloc[], and .ix[] Methods

In [12]:
companies = ["TCEHY", "BABA", "GOOG", "AAPL", "AMZN"]

p = web.DataReader(name = companies, data_source = "morningstar",
               start = "2010-01-01", end = "2016-12-31")

p

Close      High      Low     Open   Volume
Symbol Date                                                    
TCEHY  2010-01-01    4.344    4.3660    4.320    4.320        0
       2010-01-04    4.416    4.4160    4.366    4.366    61480
       2010-01-05    4.452    4.4800    4.410    4.474    75690
       2010-01-06    4.482    4.4820    4.470    4.480    56010
       2010-01-07    4.300    4.3000    4.254    4.298    49355
       2010-01-08    4.358    4.3600    4.290    4.290    25530
       2010-01-11    4.444    4.4440    4.426    4.440   133540
       2010-01-12    4.366    4.3900    4.330    4.390    66885
       2010-01-13    4.450    4.4500    4.370    4.370    34810
       2010-01-14    4.488    4.5000    4.470    4.490   271200
       2010-01-15    4.510    4.5540    4.468    4.520    69715
       2010-01-18    4.510    4.5540    4.468    4.520        0
       2010-01-19    4.224    4.2260    4.130    4.190   164935
       2010-01-20    3.960    4.0320    3.924    4.020  1448225
       2010-01-21    3.900    3.9280    3.900    3.928    61355
       2010-01-22    3.770    3.8800    3.770    3.878   291455
       2010-01-25    3.872    3.8720    3.792    3.792   229990
       2010-01-26    3.690    3.7300    3.690    3.700    72785
       2010-01-27    3.630    3.6680    3.600    3.668    89835
       2010-01-28    3.700    3.7780    3.698    3.710   173770
       2010-01-29    3.760    3.7800    3.722    3.778    26685
       2010-02-01    3.660    3.6920    3.660    3.678    37825
       2010-02-02    3.710    3.7100    3.662    3.662    26240
       2010-02-03    3.894    3.9040    3.850    3.904    37730
       2010-02-04    3.642    3.7860    3.642    3.786   134175
       2010-02-05    3.518    3.5960    3.500    3.596   302315
       2010-02-08    3.514    3.5780    3.514    3.578    97310
       2010-02-09    3.510    3.5100    3.490    3.492    31010
       2010-02-10    3.588    3.5880    3.530    3.554    94875
       2010-02-11    3.768    3.7680    3.712    3.712    40145
...                    ...       ...      ...      ...      ...
AMZN   2016-11-21  780.000  780.3500  765.110  766.000  4614574
       2016-11-22  785.330  792.4000  781.000  788.170  5311320
       2016-11-23  780.120  781.7500  773.120  781.730  3540263
       2016-11-24  780.120  780.1200  780.120  780.120        0
       2016-11-25  780.370  786.7500  777.900  786.500  1837068
       2016-11-28  766.770  777.0000  764.240  776.990  4438828
       2016-11-29  762.520  769.8900  761.320  768.000  3272344
       2016-11-30  750.570  768.0900  750.250  762.000  4625946
       2016-12-01  743.650  753.3700  738.030  752.410  4665993
       2016-12-02  740.340  748.4903  736.700  743.400  3561307
       2016-12-05  759.360  761.4900  742.000  745.000  4314723
       2016-12-06  764.720  768.2400  757.250  763.990  3794746
       2016-12-07  770.420  770.4200  755.820  764.550  3684906
       2016-12-08  767.330  773.7900  765.190  771.870  3189608
       2016-12-09  768.660  770.2500  765.340  770.000  2470923
       2016-12-12  760.120  766.8900  757.200  766.400  2963945
       2016-12-13  774.340  782.4600  762.000  764.960  5285288
       2016-12-14  768.820  780.8600  762.810  778.250  5454836
       2016-12-15  761.000  769.1000  760.310  766.280  3801927
       2016-12-16  757.770  765.1300  754.000  765.000  4848219
       2016-12-19  766.000  770.5000  756.160  758.890  3113240
       2016-12-20  771.220  774.3900  767.710  768.650  2703629
       2016-12-21  770.600  771.2200  765.700  770.000  2044629
       2016-12-22  766.340  771.2100  763.020  768.120  2543551
       2016-12-23  760.590  766.5000  757.990  764.550  1981616
       2016-12-26  760.590  760.5900  760.590  760.590        0
       2016-12-27  771.400  774.6500  761.200  763.400  2638725
       2016-12-28  772.130  780.0000  770.500  776.250  3301025
       2016-12-29  765.150  773.4000  760.850  772.400  3158299
       2016-12-30  749.870  767.3999  748.280  766.47

In [16]:
p.describe
p.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6796 entries, (TCEHY, 2010-01-01 00:00:00) to (AMZN, 2016-12-30 00:00:00)
Data columns (total 5 columns):
Close     6796 non-null float64
High      6796 non-null float64
Low       6796 non-null float64
Open      6796 non-null float64
Volume    6796 non-null int64
dtypes: float64(4), int64(1)
memory usage: 299.8+ KB


In [18]:
p.items

<bound method DataFrame.iteritems of                      Close      High      Low     Open   Volume
Symbol Date                                                    
TCEHY  2010-01-01    4.344    4.3660    4.320    4.320        0
       2010-01-04    4.416    4.4160    4.366    4.366    61480
       2010-01-05    4.452    4.4800    4.410    4.474    75690
       2010-01-06    4.482    4.4820    4.470    4.480    56010
       2010-01-07    4.300    4.3000    4.254    4.298    49355
       2010-01-08    4.358    4.3600    4.290    4.290    25530
       2010-01-11    4.444    4.4440    4.426    4.440   133540
       2010-01-12    4.366    4.3900    4.330    4.390    66885
       2010-01-13    4.450    4.4500    4.370    4.370    34810
       2010-01-14    4.488    4.5000    4.470    4.490   271200
       2010-01-15    4.510    4.5540    4.468    4.520    69715
       2010-01-18    4.510    4.5540    4.468    4.520        0
       2010-01-19    4.224    4.2260    4.130    4.190   164935
   

In [25]:
p.loc["TCEHY", "Close"]["2010-01-14"]

4.488